### ISSUE TITLE
Unable to Connect to Jfrog Artifactory SAAS instance

### ISSUE THREAD

**Issue by sudhakarteki** [1and1/go-maven-poller#11]
Hi Sir,

I am trying to configure Jfrog Artifactory SAAS instance using your plugin.

The package Repository configuration is done sucessfully but i get http 500 exception while try to configure the material in the pipeline.

Package Repository
Maven Repo URL - https://hcldevopscoe.jfrog.io/hcldevopscoe/
username - admin
password - *********

Material Configuration
Package Name* - MyPKG3
Group Id*  - libs-release-local/com
Artifact Id* - AntSpringMVC
Packaging (jar,war,ear...)* - war

libs-release-local is the repository which contains **com** as the group id and **antspringmvc** as the package id.

Please let me know how to fix this issue

**Comment by bitionaire** [comment]
Hello there,

the URL should point to the repository directly, basically show a file list when you call it within a browser. It's the same URL you would use to include the repo within your Maven or Gradle project. I'm not sure how it'll look like, but my guess is it's https://hcldevopscoe.jfrog.io/hcldevopscoe/libs-release-local/ or something like this. Then the Group Id would be just `com`. Can you check that?

**Comment by sudhakarteki** [comment]
Hi Sir,

I have put the URL as "https://hcldevopscoe.jfrog.io/hcldevopscoe/libs-release-local" in the MAVEN-REPO Repository Configuration and i am getting HTTP Status 200 Error Message.

As per my knowledge the URL should be given as "https://hcldevopscoe.jfrog.io/hcldevopscoe/" but i dont know where to provide the repository name(libs-release-local) in the arguments .

I have tried another plugin(Generic Artifactory Poller) but it has got some issues in downloading the artifacts.

**Comment by bitionaire** [comment]
Ok, sorry I'm unfamiliar with the `jfrog.io` services, therefore it's hard for me to quickly help you. Basically you need to find the URL to a file called `maven-metadata.xml` within the artifact directory of your repository. Have a look here as an example https://oss.sonatype.org/content/repositories/snapshots/com/oneandone/snmpman/. Here the group id is `com.oneandone` and the artifact id is `snmpman`. You'll see the `maven-metadata.xml` listed there. 

Maybe it's inside https://hcldevopscoe.jfrog.io/hcldevopscoe/com/ ? I'm not authorized to check that.. if so, just set the group id to `com`. 

Otherwise is there a way to get the base URL of your repository? Maybe by downloading some Maven `settings.xml` and looking into it or something like that? Or is there some info or how-to page? 
Can you browse for the _AntSpringMVC_ artifact in the tree browser and check the URLs to the files?

**Comment by sudhakarteki** [comment]
![jfrogsaas](https://cloud.githubusercontent.com/assets/5819999/17905205/bfeac590-698f-11e6-9bc2-002057b94824.PNG)

Hi Sir,
I am able to see the maven-metadata.xml file in the AntSpringMVC folder.
I have attached the snapshot of my JFrog Artifactory instance which explains the group id and the artifact id structure. 
The only challenge i have in configuring the artifactory instance is the plugin doesn't provide an option to mention the repository id(libs-releases-local)
The plugin currently supports only the onpremise version of Artifactory but not the cloud version.
Are there any chances of bringing the support to the cloud version.

**Comment by bitionaire** [comment]
As a last try, can you also check if you can access the remote browsing feature as described here https://www.jfrog.com/confluence/display/RTF/Browsing+Artifactory#BrowsingArtifactory-RemoteBrowsing ? 

I'll have a look into the main differences with the cloud version and will get back to you.

**Comment by bitionaire** [comment]
Please try release [1.1.4-alpha1](https://github.com/1and1/go-maven-poller/releases/tag/v1.1.4-alpha1) with the URL https://hcldevopscoe.jfrog.io/hcldevopscoe/libs-release-local . I just discovered an issue with the HTTP request. In case that check fails, you will find more information in the file `plugin-maven-repo.log` within the GoCD server directory / logging directory. I added some logging messages to debug the issue.

**Comment by sudhakarteki** [comment]
Hi Sir,

Thank you very much for providing the fix.

The alpha plugin now supports the cloud version of the JFROG Artifactory.

Now i am able to poll the artifacts and download them in to gocd agent machine.

**Comment by bitionaire** [comment]
Hi there,

I'm glad it worked and I could help you. 👍  
I'll check the release for the other repos and if it'll work make a final build.
