### ISSUE TITLE
Only latest revision?

### ISSUE THREAD

**Issue by esiqveland** [1and1/go-maven-poller#14]
Does this plugin only let you choose latest revision from maven for a material, or did I configure something wrong?

**Comment by bitionaire** [comment]
Hi @esiqveland 
you should be able to specify a version range from which the latest version will be polled. If that doesn't work, please copy&paste your config and we'll have a look into your issue :)

**Comment by esiqveland** [comment]
Ok, so you have to set a lower bound on the versions to include them? Then I will close this issue, but maybe note this in the readme?

**Comment by bitionaire** [comment]
As implemented by this plugin the term `latest` is equal to the highest available version in the repository.

Let's talk it through by an example. Say you have an artifact and there are multiple versions in the repo including

* _2.0_
* _1.3_
* _1.0_

When you leave the upper & lower bound blank, the plugin will always poll the latest (highest) version. Here, that's version _2.0_.

---

If you want to only use the artifacts with major version _1_, you have to set the upper bound to _2.0_. This will leave you with the list of 
* _1.3_
* _1.0_

and you're latest (highest) version is _1.3_.

---

Now the lower bound is basically useless I guess, except you want to make sure that the plugin wont use version _1.0_ even if version _1.3_ was deleted from the repository. Yet I'm not sure if that's even allowed.

---

Does this answer your question? Do you need another approach / another definition of _latest_?

**Comment by esiqveland** [comment]
Thank you for a very thorough answer!
Every build gets a version number with us, so I was just wondering where all the versions went.
We used to use the other maven-poller plugin for gocd, which shows the last 10 versions or something when you leave the lower bound blank.

It's ok, I will close this then!
