### ISSUE TITLE
Include classifier with artifacts

### ISSUE THREAD

**Issue by capeflynn** [1and1/go-maven-poller#21]
Is it possible to include a classifier when defining a package configuration?

**Comment by sfuhrm** [comment]
You mean classifiers like explained [here](https://maven.apache.org/plugins/maven-deploy-plugin/examples/deploying-with-classifiers.html)? There is no implementation like that at the moment.

**Comment by capeflynn** [comment]
Yes, that is the classifier I am referring to. Is there a suggested
solution for downloading an artifact with a classifier?

**Comment by sfuhrm** [comment]
> Is there a suggested solution for downloading an artifact with a classifier?

I have no suggestion at the moment. If you need this, feel free to submit a pull request.

**Comment by sfuhrm** [comment]
This repo has been set to read-only because we are no longer using GoCD and couldn't find another maintainer in our organization to maintain the project. Feel free to fork.
