### ISSUE TITLE
JUnit 3 & 4 style mixing

### ISSUE THREAD

**Issue by sfuhrm** [1and1/go-maven-poller#7]
* extending TextCase is JUnit 3 style
* using @Test annotation is JUnit 4

Instead of extending TestCase do

import static org.junit.Assert.*;

and then you can

assertEquals(a,b)

These files are affected:

    stephan@nucleus:~/git/go-maven-poller$ grep "extends TestCase" . -R
    ./src/test/java/com/oneandone/go/plugin/maven/client/RepositoryConnectorTest.java:public class RepositoryConnectorTest extends TestCase {
    ./src/test/java/com/oneandone/go/plugin/maven/client/RepositoryResponseHandlerTest.java:public class RepositoryResponseHandlerTest extends TestCase {
    ./src/test/java/com/oneandone/go/plugin/maven/ConfigurationProviderTest.java:public class ConfigurationProviderTest extends TestCase {
    stephan@nucleus:~/git/go-maven-poller$

**Comment by bitionaire** [comment]
Fixed with 2e650bd

**Comment by sfuhrm** [comment]
Good work!
